inputs:
  branchOrTag:
    description: 'Git branch or tag'
    default: 'No branch or tag provided'
  buildPath:
    description: 'Directory for build'
    default: 'No buildPath provided'
  pubPath:
    description: 'Directory for publish'
    default: 'No pubPath provided'
  site:
    description: 'IIS site name'
    default: 'No site provided'
  envName:
    description: 'Environment'
    default: 'No env provided'
runs:
  using: "composite"
  steps:
    # Local runner service account needs elevated to 'system'.
    - name: Shutdown site
      run: Stop-WebSite '${{ inputs.site }}'
      shell: pwsh

    - name: Publish
      run: |
        robocopy '${{ inputs.buildPath }}' '${{ inputs.pubPath }}' /s /mir /xf "Web.config"
        if( $LASTEXITCODE -ge 8 )
        {
            throw ("An error occured while copying. [RoboCopyCode: $($LASTEXITCODE)]")
        }
        else
        {
            $global:LASTEXITCODE = 0;
        }
        exit 0
      shell: pwsh

    # Local runner service account needs elevated to 'system'.
    - name: Start site
      run: Start-WebSite '${{ inputs.site }}'
      shell: pwsh
