inputs:
  solutionName:
    description: 'Name of .sln file'
    default: 'No solutionName provided'
runs:
  using: "composite"
  steps:
    - name: Restore NuGet pkgs
      run: nuget restore '${{ inputs.solutionName }}'
      shell: powershell

    - name: Build
      run: msbuild '${{ inputs.solutionName }}' /p:Configuration=Release /restore
      shell: powershell
